query ListAllEvents @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only lists general event information.") {
  events {
    id
    name
    date
    location
    description
    venueCapacity
  }
}

query GetEventDetails($id: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it retrieves details for a specific event by ID.") {
  event(id: $id) {
    id
    name
    date
    location
    description
    venueCapacity
    zones_on_event {
      id
      name
      type
      criticalCapacity
    }
  }
}

mutation CreateAlert($zoneId: UUID!, $alertType: String!, $message: String!, $status: String!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it allows them to create alerts associated with a specific zone.") {
  alert_insert(data: {
    zoneId: $zoneId,
    alertType: $alertType,
    message: $message,
    status: $status,
    timestamp_expr: "request.time"
  })
}

query GetMyZoneTelemetry($zoneId: UUID!) @auth(level: USER) {
  telemetryDatas(where: {
    zoneId: {eq: $zoneId}
  }) {
    timestamp
    dataType
    value
    source
  }
}